### ISSUE TITLE
Opracowanie systemu logowania

### ISSUE THREAD

**Issue by goszki92** [goszki92/Projekt-sklepu-internetowego-z-czesciami-samochodowymi#13]

**Comment by bengosha** [comment]
`public class LoginModel
    {
        [Required]
        [Display(Name = "Nazwa użytkownika")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Hasło")]
        public string Password { get; set; }

        [Display(Name = "Nie pamiętasz hasła?")]
        public bool RememberMe { get; set; }
    }`

**Comment by bengosha** [comment]
``

**Comment by bengosha** [comment]
`@model MvcApplication5.Models.LoginModel

@{
    ViewBag.Title = "Logowanie";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>Użyj lokalnego logowania</h2>
</hgroup>

<section id="loginForm">
@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Logowanie</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.UserName)
                @Html.TextBoxFor(m => m.UserName)
                @Html.ValidationMessageFor(m => m.UserName)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
            </li>
            <li>
                @Html.CheckBoxFor(m => m.RememberMe)
                @Html.LabelFor(m => m.RememberMe, new { @class = "checkbox" })
            </li>
        </ol>
        <input type="submit" value="Zaloguj" />
    </fieldset>
    <p>
        @Html.ActionLink("Zarejestruj", "Register") jeśli nie masz konta.
    </p>
}
</section>`

**Comment by bengosha** [comment]
`@model MvcApplication5.Models.LoginModel

@{
    ViewBag.Title = "Logowanie";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>Użyj lokalnego logowania</h2>
</hgroup>

<section id="loginForm">
@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Logowanie</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.UserName)
                @Html.TextBoxFor(m => m.UserName)
                @Html.ValidationMessageFor(m => m.UserName)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
            </li>
            <li>
                @Html.CheckBoxFor(m => m.RememberMe)
                @Html.LabelFor(m => m.RememberMe, new { @class = "checkbox" })
            </li>
        </ol>
        <input type="submit" value="Zaloguj" />
    </fieldset>
    <p>
        @Html.ActionLink("Zarejestruj", "Register") jeśli nie masz konta.
    </p>
}
</section>`
