### ISSUE TITLE
Raport klienta

### ISSUE THREAD

**Issue by goszki92** [goszki92/Projekt-sklepu-internetowego-z-czesciami-samochodowymi#3]
Raport klienta - dokument tekstowo-graficzny opisujący proces biznesowy
użytkownika i zawierający specyfikację wymagań użytkownika.

**Comment by bengosha** [comment]
Raport klienta – projekt sklepu internetowego z częściami samochodowymi.

Specyfikacja wymagań użytkownika:
a)	strona internetowa powinna wspierać działanie sklepu z częściami samochodowymi, 
b)	dodawanie nowych części do zbioru części,
c)	usuwanie części ze zbioru części,
d)	edytowanie istniejących części,
e)	dodawanie nowych kategorii części samochodowych,
f)	usuwanie kategorii części samochodowych,
g)	edytowanie kategorii części samochodowych,
h)	dodawanie statusów dostępności części,
i)	usuwanie statusów dostępności części,
j)	edytowanie statusów dostępności części,
k)	charakterystyka części:
•	marka samochodu,
•	model samochodu,
•	rok produkcji samochodu,
•	typ części,
•	rok produkcji części,
•	numer indywidualny części
l)	status części:
•	dostępna,
•	nie dostępna,
•	czasowo niedostępna
m)	kupno części:
•	data kupna,
•	rodzaj przesyłki
•	anulowanie kupna
n)	przechowywane dane pracownika:
•	imię,
•	nazwisko,
•	stanowisko,
•	numer PESEL,
•	numer i seria dowodu osobistego,
•	adres,
•	telefon,
•	wynagrodzenie
o)	przechowywane dane klienta:
•	imię,
•	nazwisko,
•	adres,
•	telefon,
•	status
p)	regulamin sklepu
•	tymczasowe zablokowanie konta klienta,
•	informacje na temat reklamacji i gwarancji,
•	bezpieczeństwo danych klienta
q)	logowanie do strony internetowej przez pracowników i klientów,
r)	wylogowanie z systemu
